version: "3.3"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "80:8080"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls

  auth:
    build: ./auth
    ports: 
      -"8000:8000"
    container_name: auth_server