version: "3.3"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "80:8080"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls

  auth:
    build: ./auth
<<<<<<< HEAD
    container_name: auth_server
=======
    container_name: auth_server
>>>>>>> 87fa5eee64761b7e39026a5a6ddbb7a7fd5ea85f
